# Generated by Django 3.2 on 2022-01-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(help_text='Enter your name', max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_No', models.CharField(help_text='Enter your phone number here', max_length=20)),
                ('Status', models.CharField(choices=[('Old', 'Old'), ('New', 'New'), ('Interested', 'Not Interested'), ('Call Back', 'Call Back'), ('Wrong Number', 'Wrong Number'), ('Fait le mac', 'Fait le mac'), ('Fond dispo', 'Fond dispo'), ('NRP', 'NRP'), ('NRP 2', 'NRP 2'), ('Ancien Interesse', 'Ancien Interesse'), ('Client', 'Client'), ('Presque Client', 'Presque Client'), ('BON Call Back', 'BON Call Back')], max_length=20)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
                ('identity', models.SlugField(max_length=10, unique=True)),
                ('Available', models.BooleanField(default=True)),
            ],
        ),
    ]
