# Generated by Django 3.2 on 2022-01-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='Profile_img',
            field=models.ImageField(default='Upload Image', help_text='If image available, please upload', upload_to='imagefolder'),
        ),
    ]
